export const COOKIE_TOKEN = 'token';

export const DATE_FORMAT = 'DD/MM/YYYY';

export const DATETIME_FORMAT = 'LTS DD/MM/YYYY';

export const QUEUE = 'queue';

export const QUEUE_JOB_NAMES = {
  MONTHLY_INVOICE: 'MONTHLY_INVOICE',
  HANDLE_LISTING: 'HANDLE_LISTING',
  HANDLE_TERMINATE_CONTRACT: 'HANDLE_TERMINATE_CONTRACT',
};
